"""add catalog number to cases

Revision ID: 2cdc0fc671e0
Revises: 94d468a50f41
Create Date: 2026-01-26 19:24:18.011174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cdc0fc671e0'
down_revision: Union[str, None] = '94d468a50f41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('cases', sa.Column('catalog_number', sa.String(length=20), nullable=True))
    
    # Update existing records with generated catalog numbers
    connection = op.get_bind()
    connection.execute(sa.text("""
        UPDATE cases 
        SET catalog_number = 'LS' || LPAD(id::text, 8, '0') 
        WHERE catalog_number IS NULL
    """))
    
    # Now make it NOT NULL
    op.alter_column('cases', 'catalog_number', nullable=False)
    op.create_index(op.f('ix_cases_catalog_number'), 'cases', ['catalog_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cases_catalog_number'), table_name='cases')
    op.drop_column('cases', 'catalog_number')
    # ### end Alembic commands ###
