"""create_refresh_tokens_table

Revision ID: 5776dbd5dd74
Revises: 860eb1a61e68
Create Date: 2026-02-09 15:45:23.631641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5776dbd5dd74'
down_revision: Union[str, None] = '860eb1a61e68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
