"""add_google_oauth_fields

Revision ID: 860eb1a61e68
Revises: 2cdc0fc671e0
Create Date: 2026-02-09 12:24:58.733096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '860eb1a61e68'
down_revision: Union[str, None] = '2cdc0fc671e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    
    # Add profile_completed as nullable first
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=True))
    
    # Update existing users to have profile_completed = True (they used email/password)
    connection = op.get_bind()
    connection.execute(sa.text("UPDATE users SET profile_completed = true WHERE profile_completed IS NULL"))
    
    # Now make it NOT NULL
    op.alter_column('users', 'profile_completed', nullable=False)
    
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
