"""add case management tables

Revision ID: 94d468a50f41
Revises: f949531a1c0f
Create Date: 2026-01-20 16:07:14.270794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94d468a50f41'
down_revision: Union[str, None] = 'f949531a1c0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_symptoms_master_id'), 'symptoms_master', ['id'], unique=False)
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.Column('practitioner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cases_id'), 'cases', ['id'], unique=False)
    op.create_index(op.f('ix_cases_practitioner_id'), 'cases', ['practitioner_id'], unique=False)
    op.create_index(op.f('ix_cases_sub_user_id'), 'cases', ['sub_user_id'], unique=False)
    op.create_index(op.f('ix_cases_user_id'), 'cases', ['user_id'], unique=False)
    op.create_table('data_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('sub_user_id', sa.Integer(), nullable=True),
    sa.Column('consent_for_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_consent_id'), 'data_consent', ['id'], unique=False)
    op.create_index(op.f('ix_data_consent_user_id'), 'data_consent', ['user_id'], unique=False)
    op.create_table('case_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('file_type', sa.String(length=10), nullable=False),
    sa.Column('s3_bucket', sa.Text(), nullable=False),
    sa.Column('s3_key', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('uploaded_by', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_files_case_id'), 'case_files', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_files_id'), 'case_files', ['id'], unique=False)
    op.create_table('case_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('practitioner_id', sa.Integer(), nullable=False),
    sa.Column('primary_diagnosis', sa.Text(), nullable=True),
    sa.Column('differential_diagnoses', sa.Text(), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practitioner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_reviews_case_id'), 'case_reviews', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_reviews_id'), 'case_reviews', ['id'], unique=False)
    op.create_table('case_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_symptoms_case_id'), 'case_symptoms', ['case_id'], unique=False)
    op.create_index(op.f('ix_case_symptoms_id'), 'case_symptoms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_case_symptoms_id'), table_name='case_symptoms')
    op.drop_index(op.f('ix_case_symptoms_case_id'), table_name='case_symptoms')
    op.drop_table('case_symptoms')
    op.drop_index(op.f('ix_case_reviews_id'), table_name='case_reviews')
    op.drop_index(op.f('ix_case_reviews_case_id'), table_name='case_reviews')
    op.drop_table('case_reviews')
    op.drop_index(op.f('ix_case_files_id'), table_name='case_files')
    op.drop_index(op.f('ix_case_files_case_id'), table_name='case_files')
    op.drop_table('case_files')
    op.drop_index(op.f('ix_data_consent_user_id'), table_name='data_consent')
    op.drop_index(op.f('ix_data_consent_id'), table_name='data_consent')
    op.drop_table('data_consent')
    op.drop_index(op.f('ix_cases_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_sub_user_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_practitioner_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_symptoms_master_id'), table_name='symptoms_master')
    op.drop_table('symptoms_master')
    # ### end Alembic commands ###
