"""Level 1 

Revision ID: f949531a1c0f
Revises: dfda8e54d91d
Create Date: 2026-01-08 15:59:46.177512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f949531a1c0f'
down_revision: Union[str, None] = 'dfda8e54d91d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('ethnicity', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('province', sa.String(length=10), nullable=False),
    sa.Column('respiratory_history', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_users_email'), 'sub_users', ['email'], unique=True)
    op.create_index(op.f('ix_sub_users_id'), 'sub_users', ['id'], unique=False)
    op.create_index(op.f('ix_sub_users_owner_user_id'), 'sub_users', ['owner_user_id'], unique=False)
    op.create_table('practitioner_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('practitioner_user_id', sa.Integer(), nullable=False),
    sa.Column('sub_user_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['practitioner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sub_user_id'], ['sub_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practitioner_assignments_id'), 'practitioner_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_practitioner_assignments_practitioner_user_id'), 'practitioner_assignments', ['practitioner_user_id'], unique=False)
    op.create_index(op.f('ix_practitioner_assignments_sub_user_id'), 'practitioner_assignments', ['sub_user_id'], unique=False)
    op.drop_index('ix_patients_user_id', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_practitioners_user_id', table_name='practitioners')
    op.drop_table('practitioners')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('sex', sa.String(length=1), nullable=True))
    op.add_column('users', sa.Column('ethnicity', sa.String(length=3), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('province', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('practitioner_id', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('institution', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('institution_location_country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('institution_location_province', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('respiratory_history', sa.Text(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['practitioner_id'])
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('users', 'respiratory_history')
    op.drop_column('users', 'institution_location_province')
    op.drop_column('users', 'institution_location_country')
    op.drop_column('users', 'institution')
    op.drop_column('users', 'practitioner_id')
    op.drop_column('users', 'province')
    op.drop_column('users', 'country')
    op.drop_column('users', 'ethnicity')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'age')
    op.drop_column('users', 'deleted_at')
    op.create_table('practitioners',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('practitioner_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institution', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('institution_location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='practitioners_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='practitioners_pkey'),
    sa.UniqueConstraint('practitioner_id', name='practitioners_practitioner_id_key')
    )
    op.create_index('ix_practitioners_user_id', 'practitioners', ['user_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ethnicity', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='patients_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patients_pkey')
    )
    op.create_index('ix_patients_user_id', 'patients', ['user_id'], unique=True)
    op.drop_index(op.f('ix_practitioner_assignments_sub_user_id'), table_name='practitioner_assignments')
    op.drop_index(op.f('ix_practitioner_assignments_practitioner_user_id'), table_name='practitioner_assignments')
    op.drop_index(op.f('ix_practitioner_assignments_id'), table_name='practitioner_assignments')
    op.drop_table('practitioner_assignments')
    op.drop_index(op.f('ix_sub_users_owner_user_id'), table_name='sub_users')
    op.drop_index(op.f('ix_sub_users_id'), table_name='sub_users')
    op.drop_index(op.f('ix_sub_users_email'), table_name='sub_users')
    op.drop_table('sub_users')
    # ### end Alembic commands ###
