// src/constants/privacyPolicy.ts
// Single source of truth for LungSense Terms of Use & Medical Disclaimer.
// Import PRIVACY_SECTIONS wherever the policy needs to be displayed.

export const PRIVACY_META = {
  title: "Terms of Use & Medical Disclaimer",
  lastUpdated: "March 11, 2026",
  company: "DigiBiomics Inc.",
  contact: "info@digibiomics.com",
};

export const PRIVACY_SECTIONS = [
  {
    heading: "1. About LungSense",
    body: `LungSense is an AI-powered respiratory screening and monitoring platform that analyzes health data including:
• cough recordings
• respiratory audio signals
• physiological monitoring data
• medical images (e.g., chest X-rays)
• symptom inputs, demographic data, and health information

The system generates algorithmic insights, risk scores, and decision-support outputs related to lung health.

The Service may be used by:
• individuals
• healthcare professionals
• care givers at home or facility
• hospitals and research organizations`,
  },
  {
    heading: "2. Important Medical Disclaimer",
    body: `The Service does not provide medical advice, diagnosis, or treatment.

The outputs generated by LungSense are AI-generated predictions or decision-support insights and may include probabilistic estimates.

The Service is intended for:
• Screening
• Research
• Monitoring
• risk score and decision-support
• triaging

and must not be used as the sole basis for medical decisions.

Users should always consult a qualified healthcare professional before making any medical decision.

In case of a medical emergency, users should contact local emergency services immediately.`,
  },
  {
    heading: "3. Clinical Responsibility",
    body: `Healthcare professionals using LungSense remain fully responsible for all clinical decisions and patient care.

LungSense is designed to assist clinical workflows, not replace medical judgment.

DigiBiomics does not practice medicine and does not provide clinical services.`,
  },
  {
    heading: "4. Use of Artificial Intelligence",
    body: `The Service uses machine learning and artificial intelligence models trained on large datasets.

AI outputs may include:
• predicted risk scores
• disease likelihood estimates
• screening alerts
• monitoring insights
• Exacerbation risk and chances

AI outputs may occasionally contain errors, inaccuracies, or incomplete interpretations.

Users acknowledge that:
• AI predictions are not guaranteed to be correct
• model performance may vary across populations
• final interpretation must involve human judgment`,
  },
  {
    heading: "5. Acceptable Use",
    body: `You agree not to:
• use the Service for illegal purposes
• upload false or misleading medical data
• attempt to reverse engineer the platform
• interfere with system security or operations
• misuse AI outputs for automated diagnosis without human oversight

DigiBiomics reserves the right to suspend accounts that violate these Terms.`,
  },
  {
    heading: "6. Data Use and AI Model Development",
    body: `By using the Service, you agree that DigiBiomics may process submitted data to:
• operate the platform
• improve AI model accuracy
• conduct algorithm training and validation
• perform system monitoring and quality assurance
• support regulatory compliance
• conduct scientific research and publications

Data used for these purposes may be:
• de-identified
• Anonymized
• Aggregated
• transformed for machine learning development

DigiBiomics will implement safeguards to protect user privacy.`,
  },
  {
    heading: "7. Data Ownership",
    body: `Users retain ownership of the data they submit.

However, by submitting data to the Service, users grant DigiBiomics a non-exclusive, worldwide, royalty-free license to use such data for:
• providing the Service
• AI model development
• research and analytics
• regulatory and safety obligations

De-identified datasets may be retained indefinitely for research and algorithm improvement and can be shared with third parties for further R&D.`,
  },
  {
    heading: "8. Research and Scientific Use",
    body: `De-identified or aggregated data may be used for:
• clinical research
• validation studies
• algorithm benchmarking
• academic publications
• regulatory submissions
• Developing new healthcare products with partner companies or organizations

No identifiable personal data will be disclosed without appropriate legal permissions.`,
  },
  {
    heading: "9. Data De-Identification",
    body: `DigiBiomics may remove identifiers from data to create de-identified datasets.

Once de-identified, such data:
• cannot reasonably be linked back to individuals
• may be used for research, analytics, and AI development`,
  },
  {
    heading: "10. Security",
    body: `DigiBiomics implements security measures including:
• encryption in transit and at rest
• access controls
• audit logging
• cybersecurity monitoring
• secure AI pipelines

However, no system can guarantee absolute security.`,
  },
  {
    heading: "11. Regulatory Compliance",
    body: `The LungSense platform may be subject to regulations governing Software as a Medical Device (SaMD).

We aim to comply with applicable regulatory frameworks including:
• Health Canada
• FDA (United States)
• EU MDR
• UK MHRA
• applicable global AI and privacy laws

Regulatory status may vary by region.`,
  },
  {
    heading: "12. Third-Party Services",
    body: `The Service may rely on third-party providers such as:
• cloud infrastructure providers
• analytics platforms
• security monitoring services

These providers operate under contractual data protection obligations.`,
  },
  {
    heading: "13. International Use",
    body: `LungSense may be accessed globally. Users are responsible for ensuring that their use complies with local laws and regulations.`,
  },
  {
    heading: "14. Limitation of Liability",
    body: `To the fullest extent permitted by law, DigiBiomics Inc. and its affiliates shall not be liable for:
• medical decisions made using the Service
• reliance on AI-generated outputs
• data inaccuracies or incomplete results
• system interruptions or service outages
• indirect, incidental, or consequential damages

The Service is provided "as is" and "as available."

Use of the Service is at the user's own risk.`,
  },
  {
    heading: "15. Indemnification",
    body: `Users agree to indemnify and hold harmless DigiBiomics from claims arising from:
• misuse of the Service
• violation of these Terms
• improper clinical use of AI outputs`,
  },
  {
    heading: "16. Changes to the Service",
    body: `DigiBiomics may modify or discontinue parts of the Service at any time.`,
  },
  {
    heading: "17. Changes to These Terms",
    body: `We may update these Terms periodically.

Continued use of the Service after updates constitutes acceptance of the revised Terms.`,
  },
  {
    heading: "18. Governing Law",
    body: `These Terms shall be governed by the laws of:
Province of Ontario, Canada
without regard to conflict-of-law principles.`,
  },
  {
    heading: "19. Contact Information",
    body: `DigiBiomics Inc.
3052 Owls Foot Dr
Mississauga, ON L5M 6W5
Canada
Email: info@digibiomics.com`,
  },
];